services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=file:/app/prisma/data/app.db
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/prisma/data/app.db
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
      - ./public/audio:/app/public/audio
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["sh","-lc","npx prisma db push --accept-data-loss && npm run start"]
